{
 "title": "SQS.Extensions",
 "time": { "from": "2023-08-19T08:31:49.450Z", "to": "2023-08-19T10:09:01.708Z" },
 "templating": {
  "list": [
   { "name": "app", "label": "Application", "query": { "query": "label_values(app)" } },
   {
    "name": "interval",
    "label": "Interval",
    "query": "30s,1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Total successful messages ",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum without (messaging_type) (rate(sqs_extensions_messaging_successes{app=~\"[[app]]\"}[$interval])*100)"
    }
   ]
  },
  {
   "title": "Average error msg ",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "rate(sqs_extensions_messaging_failures{app=~\"[[app]]\"}[$interval])*100"
    }
   ]
  },
  {
   "title": "Messages deleted",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "rate(sqs_extensions_messaging_deleted{app=~\"[[app]]\"}[$interval])*100",
     "legendFormat": "{{sqs_extensions_message_type}}"
    }
   ]
  },
  {
   "title": "Average msg ",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "rate(sqs_extensions_messaging_successes{app=~\"[[app]]\"}[$interval])*100"
    }
   ]
  },
  {
   "title": "Processed messages",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(sqs_extensions_messaging_successes{app=~\"[[app]]\"}[$interval])*100"
    }
   ]
  },
  {
   "title": "Fetched messages",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(sqs_extensions_messaging_fetches{app=~\"[[app]]\"}[$interval])*100"
    }
   ]
  },
  {
   "title": "Failed messages",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(sqs_extensions_messaging_failures{app=~\"[[app]]\"}[$interval]) * 100"
    }
   ]
  }
 ]
}